#!/usr/bin/env python3
"""Create a portable, searchable HTML reference with embedded OpenAPI and guide downloads."""
from pathlib import Path
import json,sys,html
ROOT=Path(__file__).resolve().parents[2]
spec=json.loads((ROOT/'InitializrSpringbootProjectFresh/src/main/resources/api-reference/merchant-openapi.json').read_text())
guide=(ROOT/'Docs/Api/Cito-Gateway-Integration-Guide.md').read_text()
try:
 import markdown2
 guide_html=markdown2.markdown(guide,extras=['tables','fenced-code-blocks','header-ids'])
except ImportError:
 guide_html='<pre>'+html.escape(guide)+'</pre>'
data=json.dumps({'spec':spec,'guide':guide},ensure_ascii=False).replace('<','\\u003c')
content='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Cito Gateway API Reference</title>
<style>
:root{font-family:Inter,system-ui,Arial,sans-serif;color:#0b2545;background:#f8fafc;line-height:1.55}*{box-sizing:border-box}body{margin:0}header{background:#0b2545;color:white;padding:38px max(22px,5vw)}h1{font-size:clamp(28px,4vw,44px);line-height:1.15;margin:6px 0 16px}header p{max-width:900px;color:#d8e7fa}.eyebrow{color:#8fcaff;text-transform:uppercase;letter-spacing:.12em;font-size:13px;font-weight:700}.bar{position:sticky;top:0;background:#fff;border-bottom:1px solid #c7d6e8;padding:14px max(22px,5vw);z-index:2;display:flex;gap:12px;flex-wrap:wrap;align-items:center}input,button,select{font:inherit;min-height:44px;border:1px solid #64748b;border-radius:8px;padding:9px 12px;color:#0b2545;background:white}input{min-width:240px;flex:1}button{cursor:pointer}button.active{background:#0047b3;color:#fff;border-color:#0047b3}:focus-visible{outline:3px solid #0066ff;outline-offset:3px}main{max-width:1450px;margin:auto;padding:24px max(22px,5vw)}#guide{max-width:1000px}#guide h2{padding-top:14px;color:#0047b3}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#edf4fc;padding:16px;border-radius:8px;font-size:13px;max-height:550px;overflow:auto}table{border-collapse:collapse;display:block;overflow:auto;width:100%;font-size:14px}th,td{padding:12px;border:1px solid #c7d6e8;text-align:left;vertical-align:top}th{background:#e6f2ff}details{background:#fff;border:1px solid #c7d6e8;border-radius:12px;padding:14px 18px;margin:12px 0;overflow-wrap:anywhere}summary{cursor:pointer;min-height:36px;font-weight:650}summary strong{display:inline-block;min-width:65px;color:#0047b3}small{color:#475569}.meta{display:flex;gap:12px;flex-wrap:wrap;color:#475569;font-size:13px}.badge{background:#e6f2ff;padding:4px 9px;border-radius:5px}a{color:#0047b3}#empty{font-size:18px;padding:25px}.note{border-left:4px solid #0066ff;padding:12px 16px;background:#e6f2ff}footer{border-top:1px solid #c7d6e8;padding:24px max(22px,5vw);color:#475569;font-size:13px}@media(max-width:600px){input{min-width:0;width:100%;flex-basis:100%}.bar{position:static}main{padding:16px}details{padding:12px}table{font-size:12px}}@media print{.bar,button{display:none}header{background:#fff;color:#0b2545}header p{color:#0b2545}main{max-width:none}details{break-inside:avoid}pre{max-height:none}#guide{display:block!important}}
</style></head><body><header><div class="eyebrow">Cito Gateway · Developer documentation</div><h1>Connect securely.<br>Build with clear contracts.</h1><p>Searchable API operations, request and response schemas, authentication guidance, webhook handling and endpoint access billing.</p><p>Reference version 2.0 · 10 September 2026 · Repository change awaiting deployment verification</p></header>
<div class="bar"><button id="show-guide" class="active">Integration guide</button><button id="show-api">API reference</button><input id="search" type="search" aria-label="Search guide and API functions" placeholder="Search authentication, collect, webhook, pricing…"><button id="download-api">Download OpenAPI JSON</button><button id="download-guide">Download guide</button></div>
<main><p class="note">Current rates and enabled services are available in your merchant portal. This offline reference contains no credentials and cannot execute API calls. Administrator-only APIs are intentionally excluded.</p><p id="count" role="status"></p><article id="guide">'''+guide_html+'''</article><section id="api" aria-label="API operations" hidden></section><p id="empty" hidden>No results. Try an HTTP method, endpoint path, feature or field name.</p></main><footer>Cito brand standard 1.2 · Generated from the repository's owning API contracts. Code and documentation do not establish provider certification or production activation.</footer>
<script type="application/json" id="data">'''+data+'''</script><script>
const data=JSON.parse(document.getElementById('data').textContent), api=document.getElementById('api'), guide=document.getElementById('guide'), query=document.getElementById('search');let active='guide';
const methods=new Set(['get','post','put','patch','delete','head','options']);
function node(tag,text){const el=document.createElement(tag);el.textContent=text;return el}
function detail(label,value){const d=node('details','');d.append(node('summary',label),node('pre',JSON.stringify(value,null,2)));return d}
const records=[];
for(const [path,item] of Object.entries(data.spec.paths))for(const [method,op] of Object.entries(item)){if(!methods.has(method))continue;const el=node('details','');const summary=node('summary','');summary.append(node('strong',method.toUpperCase()),document.createTextNode(' '+path+' — '+(op.summary||op.operationId)));el.append(summary);el.append(node('p',op.description||op.summary||''));const meta=node('p','Audience: '+op['x-cito-audience']+' · Access unit: authenticated request · Initial rate: UGX 0.0000 (check live rates)');meta.className='meta';el.append(meta);el.append(detail('Authentication',op.security));if(op.parameters)el.append(detail('Parameters',op.parameters));if(op.requestBody)el.append(detail('Request body',op.requestBody));el.append(detail('Responses and errors',op.responses));const schemas=node('details','');schemas.append(node('summary','Schema dictionary'));
const refs=new Set();function collect(x){if(Array.isArray(x)){x.forEach(collect);return}if(x&&typeof x==='object'){if(x.$ref&&x.$ref.startsWith('#/components/')&&!refs.has(x.$ref)){refs.add(x.$ref);let v=data.spec;for(const key of x.$ref.slice(2).split('/'))v=v[key.replace(/~1/g,'/').replace(/~0/g,'~')];schemas.append(detail(x.$ref,v));collect(v)}Object.values(x).forEach(collect)}}collect(op);el.append(schemas);api.append(el);records.push({el,text:(method+' '+path+' '+JSON.stringify(op)).toLowerCase()})}
function filter(){const text=query.value.toLowerCase();guide.hidden=active!=='guide';api.hidden=active!=='api';let count=0;if(active==='api'){records.forEach(r=>{r.el.hidden=!r.text.includes(text);if(!r.el.hidden)count++})}else{const matches=!text||guide.textContent.toLowerCase().includes(text);guide.hidden=!matches;count=matches?1:0}document.getElementById('empty').hidden=count>0;document.getElementById('count').textContent=active==='api'?count+' of '+records.length+' API operations':text?'Guide search: '+(count?'matching text found; use your browser Find for exact occurrences':'no matching text'): '12 practical integration sections';}
for(const value of ['guide','api'])document.getElementById('show-'+value).onclick=()=>{active=value;for(const v of ['guide','api'])document.getElementById('show-'+v).classList.toggle('active',v===active);filter()};query.oninput=filter;
function save(name,content,type){const url=URL.createObjectURL(new Blob([content],{type}));const a=node('a','');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}document.getElementById('download-api').onclick=()=>save('Cito-Gateway-OpenAPI.json',JSON.stringify(data.spec,null,2),'application/json');document.getElementById('download-guide').onclick=()=>save('Cito-Gateway-Integration-Guide.md',data.guide,'text/markdown');filter();
</script></body></html>'''
path=Path(sys.argv[1]);path.parent.mkdir(parents=True,exist_ok=True);path.write_text(content);print(path)
