CREATE TABLE airtel_recovery (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    provider_reference VARCHAR(128) NOT NULL,
    merchant_id BIGINT NOT NULL,
    merchant_number VARCHAR(128) NOT NULL,
    merchant_reference VARCHAR(191) NOT NULL,
    transaction_id BIGINT NULL,
    operation VARCHAR(16) NOT NULL,
    environment VARCHAR(16) NOT NULL,
    country_code VARCHAR(8) NOT NULL,
    currency_code VARCHAR(8) NOT NULL,
    credential_source VARCHAR(32) NOT NULL,
    credential_identity VARCHAR(96) NOT NULL,
    amount DECIMAL(19,4) NOT NULL,
    request_hash VARCHAR(96) NOT NULL,
    callback_url TEXT NULL,
    recovery_state VARCHAR(16) NOT NULL DEFAULT 'PREPARED',
    terminal_status VARCHAR(16) NULL,
    financial_reference VARCHAR(191) NULL,
    attempt_count INT NOT NULL DEFAULT 0,
    last_code VARCHAR(96) NULL,
    submission_rejection VARCHAR(48) NULL,
    next_poll_at DATETIME(6) NOT NULL,
    claim_token VARCHAR(36) NULL,
    claim_until DATETIME(6) NULL,
    last_signal_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    UNIQUE KEY uq_airtel_provider_reference (provider_reference),
    UNIQUE KEY uq_airtel_merchant_reference (merchant_id,environment,merchant_reference),
    KEY idx_airtel_recovery_due (recovery_state,next_poll_at,claim_until),
    CONSTRAINT ck_airtel_recovery_amount CHECK (amount>0),
    CONSTRAINT ck_airtel_recovery_operation CHECK (operation IN ('COLLECT','PAYOUT')),
    CONSTRAINT ck_airtel_recovery_environment CHECK (environment IN ('SANDBOX','PRODUCTION')),
    CONSTRAINT ck_airtel_recovery_state CHECK (recovery_state IN ('PREPARED','READY','REVIEW','RESOLVED')),
    CONSTRAINT ck_airtel_recovery_source CHECK (credential_source IN ('MERCHANT','PLATFORM_SHARED','LEGACY_MERCHANT','LEGACY_PLATFORM'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
